### PR TITLE
phpstan swap service container for specific data service

### PR DESCRIPTION
**Pull request by dameert**

### CODE REVIEW

**Comment by theus77** [comment]
Have you tried this refactoring? If I added this it was because I faced some circle references. I'll try on my own tonight

**Comment by dameert** [comment]
I did not try it. But circle references seem strange in this case. If you have an error, post it here and I will look into it.

**Comment by dameert** [comment]
I tried and php bin/console c:cl passes without errors.

**Comment by theus77** [comment]
I tried, it works now. Good news.

**Pull request merged**
