### PR TITLE
Fix ajax form errors

### PR DESCRIPTION
**Pull request by laurensmertens**

### CODE REVIEW

**Comment by laurensmertens** [comment]
@dameert or @theus77 please check this one too, the form validation on ajax callback is currently broken.

**Comment by laurensmertens** [comment]
@dameert Can you check (not super urgent, but has been pending for a while now). Thx

**Comment by dameert** [comment]
Can you split up the style changes from the functional changes? This is too hard too review. + also resolve the conflicts with master. —thx

**Comment by laurensmertens** [comment]
Done: https://github.com/ems-project/EMSCoreBundle/pull/263

**Pull request closed without merging**
