### PR TITLE
WIP: Demo isa env export

### PR DESCRIPTION
**Pull request by IsaMic**
WIP - add export env link ems-project/elasticms#74 - need refactor of jsonNormalizer

### CODE REVIEW

**Comment by dameert** [comment]
Sprint for makerbundle got stopped. This code should be rebased as the implementation for exporting and importing contentTypes is differently implemented.

**Comment by Davidmattei** [comment]
@dameert @IsaMic can we close this PR ?

**Comment by dameert** [comment]
we keep it open as a starting point to reboot the development on makerbundle

**Comment by dameert** [comment]
We kan find this pr in the history if ever needed

**Pull request closed without merging**
