### PR TITLE
fix: the release word is reserved in MariaDB/MySQL, it has to be escaped

### PR DESCRIPTION
**Pull request by theus77**
|Q              |A  |
|---------------|---|
|Bug fix?       |y|
|New feature?   |n|	
|BC breaks?     |n|	
|Deprecations?  |n|	
|Fixed tickets  |n|

### CODE REVIEW

**Comment by Davidmattei** [comment]
Mmm this one is tricking, should we not just rename the table?

**Review by Davidmattei — CHANGES_REQUESTED** [review]
Should we not just rename the table

**Comment by theus77** [comment]
> Should we not just rename the table

Any suggestion?

**Comment by Davidmattei** [comment]
> > Should we not just rename the table
> 
> Any suggestion?

A release is a collection of Revisions with a source and target environment.
So may 'revision_release'

**Comment by theus77** [comment]
> > > Should we not just rename the table
> > 
> > 
> > Any suggestion?
> 
> A release is a collection of Revisions with a source and target environment. So may 'revision_release'

A relation table release_revision already exist. So I go for release_entity

**Review by Davidmattei — APPROVED** [review]

**Pull request merged**
